### ISSUE TITLE
kvm vnc keymap dropped after nfs mount attempt

### ISSUE THREAD

**Issue by sgsax** [ganeti/ganeti#1299] opened 2018-05-04 21:06 UTC
After attempting to mount NFS share on a node, remote connections to an instance over VNC have no usable keymap. The NFS mount doesn't need to heave been completed, only attempted. If I duplicate the parameters passed by ganeti wrapper scripts to qemu and execute it directly, the keymap is fine. The keymap is only dropped when using the ganeti framework. After the NFS mount has been attempted even once, the broken state persists after restart of services and even reboot of the node. Manually setting the keymap, either by setting it in the hypervisor configuration or adding it to kvm_extra, does not resolve the issue.

By enabling debug logging for KVM, I can show the following results (same keystrokes were sent in each):
Before NFS mount: https://pastebin.com/rDPXYZ5r
After NFS mount: https://pastebin.com/kgvZtrnv
You can see some keys work (including typographic and numeric keys), but most do not (namely alphabetic keys).

I have taken before and after snapshots of the filesystem of the node and diff'ed the results to see what files might have changed to trigger the permanent change to the system state. This has not turned up any useful results.

I have not tested with mounting other filesystem types. Initial mount of system disk does not appear to cause the failure.

I realize this makes no sense and there should be no connection, and yet I can duplicate this readily and consistently and have done so with multiple OS distros and releases on the node (test results matrix: https://pastebin.com/9pz08F4a). These were all vanilla installs, only adding dependency packages for ganeti and bare minimum of configuration. I've also tried multiple VNC clients from multiple OS.

I've worked with people on both #qemu and #ganeti irc channels to get debugging data and strategies for testing. I also discussed the issue in the forum: https://groups.google.com/forum/#!topic/ganeti/E-rBvjTv8TQ. I am happy to provide additional information and do additional testing if there is anything else you can suggest.

**Comment by sgsax** [comment] 2018-05-04 21:09
In case the pastebin links break, here's the debug log for key codes captured before NFS mount:
`25881@1525122543.135069:vnc_key_event_map down 1, sym 0xff54 -> keycode 0xd0 [down]
25881@1525122543.214231:vnc_key_event_map down 0, sym 0xff54 -> keycode 0xd0 [down]
25881@1525122543.310200:vnc_key_event_map down 1, sym 0xff54 -> keycode 0xd0 [down]
25881@1525122543.382062:vnc_key_event_map down 0, sym 0xff54 -> keycode 0xd0 [down]
25881@1525122543.486180:vnc_key_event_map down 1, sym 0xff54 -> keycode 0xd0 [down]
25881@1525122543.558047:vnc_key_event_map down 0, sym 0xff54 -> keycode 0xd0 [down]
25881@1525122543.662243:vnc_key_event_map down 1, sym 0xff54 -> keycode 0xd0 [down]
25881@1525122543.734062:vnc_key_event_map down 0, sym 0xff54 -> keycode 0xd0 [down]
25881@1525122543.870360:vnc_key_event_map down 1, sym 0xff54 -> keycode 0xd0 [down]
25881@1525122543.949966:vnc_key_event_map down 0, sym 0xff54 -> keycode 0xd0 [down]
25881@1525122544.262378:vnc_key_event_map down 1, sym 0xff52 -> keycode 0xc8 [up]
25881@1525122544.334038:vnc_key_event_map down 0, sym 0xff52 -> keycode 0xc8 [up]
25881@1525122544.438185:vnc_key_event_map down 1, sym 0xff52 -> keycode 0xc8 [up]
25881@1525122544.510036:vnc_key_event_map down 0, sym 0xff52 -> keycode 0xc8 [up]
25881@1525122544.622124:vnc_key_event_map down 1, sym 0xff52 -> keycode 0xc8 [up]
25881@1525122544.694102:vnc_key_event_map down 0, sym 0xff52 -> keycode 0xc8 [up]
25881@1525122544.806238:vnc_key_event_map down 1, sym 0xff52 -> keycode 0xc8 [up]
25881@1525122544.902048:vnc_key_event_map down 0, sym 0xff52 -> keycode 0xc8 [up]
25881@1525122545.030350:vnc_key_event_map down 1, sym 0xff52 -> keycode 0xc8 [up]
25881@1525122545.126020:vnc_key_event_map down 0, sym 0xff52 -> keycode 0xc8 [up]
25881@1525122546.582447:vnc_key_event_map down 1, sym 0x71 -> keycode 0x10 [q]
25881@1525122546.702048:vnc_key_event_map down 0, sym 0x71 -> keycode 0x10 [q]
25881@1525122546.878332:vnc_key_event_map down 1, sym 0x77 -> keycode 0x11 [w]
25881@1525122546.957961:vnc_key_event_map down 0, sym 0x77 -> keycode 0x11 [w]
25881@1525122547.078181:vnc_key_event_map down 1, sym 0x65 -> keycode 0x12 [e]
25881@1525122547.181980:vnc_key_event_map down 0, sym 0x65 -> keycode 0x12 [e]
25881@1525122547.270351:vnc_key_event_map down 1, sym 0x72 -> keycode 0x13 [r]
25881@1525122547.358038:vnc_key_event_map down 0, sym 0x72 -> keycode 0x13 [r]
25881@1525122547.878365:vnc_key_event_map down 1, sym 0x61 -> keycode 0x1e [a]
25881@1525122547.974024:vnc_key_event_map down 0, sym 0x61 -> keycode 0x1e [a]
25881@1525122548.094325:vnc_key_event_map down 1, sym 0x73 -> keycode 0x1f [s]
25881@1525122548.182013:vnc_key_event_map down 0, sym 0x73 -> keycode 0x1f [s]
25881@1525122548.334341:vnc_key_event_map down 1, sym 0x64 -> keycode 0x20 [d]
25881@1525122548.485964:vnc_key_event_map down 0, sym 0x64 -> keycode 0x20 [d]
25881@1525122548.486069:vnc_key_event_map down 1, sym 0x66 -> keycode 0x21 [f]
25881@1525122548.550022:vnc_key_event_map down 0, sym 0x66 -> keycode 0x21 [f]
25881@1525122548.966263:vnc_key_event_map down 1, sym 0x7a -> keycode 0x2c [z]
25881@1525122549.077995:vnc_key_event_map down 0, sym 0x7a -> keycode 0x2c [z]
25881@1525122549.206139:vnc_key_event_map down 1, sym 0x78 -> keycode 0x2d [x]
25881@1525122549.301967:vnc_key_event_map down 0, sym 0x78 -> keycode 0x2d [x]
25881@1525122549.454426:vnc_key_event_map down 1, sym 0x63 -> keycode 0x2e [c]
25881@1525122549.525986:vnc_key_event_map down 0, sym 0x63 -> keycode 0x2e [c]
25881@1525122549.654220:vnc_key_event_map down 1, sym 0x76 -> keycode 0x2f [v]
25881@1525122549.734004:vnc_key_event_map down 0, sym 0x76 -> keycode 0x2f [v]
25881@1525122550.222340:vnc_key_event_map down 1, sym 0x2d -> keycode 0xc [minus]
25881@1525122550.302032:vnc_key_event_map down 0, sym 0x2d -> keycode 0xc [minus]
25881@1525122550.390153:vnc_key_event_map down 1, sym 0x2d -> keycode 0xc [minus]
25881@1525122550.469902:vnc_key_event_map down 0, sym 0x2d -> keycode 0xc [minus]
25881@1525122550.566196:vnc_key_event_map down 1, sym 0x2d -> keycode 0xc [minus]
25881@1525122550.662012:vnc_key_event_map down 0, sym 0x2d -> keycode 0xc [minus]
25881@1525122550.822265:vnc_key_event_map down 1, sym 0x3d -> keycode 0xd [equal]
25881@1525122550.894084:vnc_key_event_map down 0, sym 0x3d -> keycode 0xd [equal]
25881@1525122550.990139:vnc_key_event_map down 1, sym 0x3d -> keycode 0xd [equal]
25881@1525122551.077964:vnc_key_event_map down 0, sym 0x3d -> keycode 0xd [equal]
25881@1525122551.190098:vnc_key_event_map down 1, sym 0x3d -> keycode 0xd [equal]
25881@1525122551.270009:vnc_key_event_map down 0, sym 0x3d -> keycode 0xd [equal]
qemu-system-x86_64: terminating on signal 15 from pid 25904 (/usr/bin/python)`

**Comment by sgsax** [comment] 2018-05-04 21:10
Debug log for key codes captured after NFS mount:
`26054@1525122633.453725:vnc_key_event_map down 1, sym 0xff54 -> keycode 0x0 [power]
26054@1525122633.541136:vnc_key_event_map down 0, sym 0xff54 -> keycode 0x0 [power]
26054@1525122633.669329:vnc_key_event_map down 1, sym 0xff54 -> keycode 0x0 [power]
26054@1525122633.749152:vnc_key_event_map down 0, sym 0xff54 -> keycode 0x0 [power]
26054@1525122633.885283:vnc_key_event_map down 1, sym 0xff54 -> keycode 0x0 [power]
26054@1525122633.957168:vnc_key_event_map down 0, sym 0xff54 -> keycode 0x0 [power]
26054@1525122634.109353:vnc_key_event_map down 1, sym 0xff54 -> keycode 0x0 [power]
26054@1525122634.181219:vnc_key_event_map down 0, sym 0xff54 -> keycode 0x0 [power]
26054@1525122634.341437:vnc_key_event_map down 1, sym 0xff54 -> keycode 0x0 [power]
26054@1525122634.413189:vnc_key_event_map down 0, sym 0xff54 -> keycode 0x0 [power]
26054@1525122634.909335:vnc_key_event_map down 1, sym 0xff52 -> keycode 0x0 [power]
26054@1525122634.997206:vnc_key_event_map down 0, sym 0xff52 -> keycode 0x0 [power]
26054@1525122635.149379:vnc_key_event_map down 1, sym 0xff52 -> keycode 0x0 [power]
26054@1525122635.253256:vnc_key_event_map down 0, sym 0xff52 -> keycode 0x0 [power]
26054@1525122635.381328:vnc_key_event_map down 1, sym 0xff52 -> keycode 0x0 [power]
26054@1525122635.469158:vnc_key_event_map down 0, sym 0xff52 -> keycode 0x0 [power]
26054@1525122635.581396:vnc_key_event_map down 1, sym 0xff52 -> keycode 0x0 [power]
26054@1525122635.677201:vnc_key_event_map down 0, sym 0xff52 -> keycode 0x0 [power]
26054@1525122635.845228:vnc_key_event_map down 1, sym 0xff52 -> keycode 0x0 [power]
26054@1525122635.941179:vnc_key_event_map down 0, sym 0xff52 -> keycode 0x0 [power]
Warning: no scancode found for keysym 113
26054@1525122636.565378:vnc_key_event_map down 1, sym 0x71 -> keycode 0x0 [power]
Warning: no scancode found for keysym 113
26054@1525122636.669174:vnc_key_event_map down 0, sym 0x71 -> keycode 0x0 [power]
Warning: no scancode found for keysym 119
26054@1525122636.797373:vnc_key_event_map down 1, sym 0x77 -> keycode 0x0 [power]
Warning: no scancode found for keysym 119
26054@1525122636.885245:vnc_key_event_map down 0, sym 0x77 -> keycode 0x0 [power]
Warning: no scancode found for keysym 101
26054@1525122637.013278:vnc_key_event_map down 1, sym 0x65 -> keycode 0x0 [power]
Warning: no scancode found for keysym 101
26054@1525122637.101224:vnc_key_event_map down 0, sym 0x65 -> keycode 0x0 [power]
Warning: no scancode found for keysym 114
26054@1525122637.213335:vnc_key_event_map down 1, sym 0x72 -> keycode 0x0 [power]
Warning: no scancode found for keysym 114
26054@1525122637.301252:vnc_key_event_map down 0, sym 0x72 -> keycode 0x0 [power]
Warning: no scancode found for keysym 97
26054@1525122637.453406:vnc_key_event_map down 1, sym 0x61 -> keycode 0x0 [power]
Warning: no scancode found for keysym 97
26054@1525122637.557192:vnc_key_event_map down 0, sym 0x61 -> keycode 0x0 [power]
Warning: no scancode found for keysym 115
26054@1525122637.661318:vnc_key_event_map down 1, sym 0x73 -> keycode 0x0 [power]
Warning: no scancode found for keysym 115
26054@1525122637.749195:vnc_key_event_map down 0, sym 0x73 -> keycode 0x0 [power]
Warning: no scancode found for keysym 100
26054@1525122637.917361:vnc_key_event_map down 1, sym 0x64 -> keycode 0x0 [power]
Warning: no scancode found for keysym 100
26054@1525122638.005201:vnc_key_event_map down 0, sym 0x64 -> keycode 0x0 [power]
Warning: no scancode found for keysym 102
26054@1525122638.109346:vnc_key_event_map down 1, sym 0x66 -> keycode 0x0 [power]
Warning: no scancode found for keysym 102
26054@1525122638.181163:vnc_key_event_map down 0, sym 0x66 -> keycode 0x0 [power]
Warning: no scancode found for keysym 122
26054@1525122638.357358:vnc_key_event_map down 1, sym 0x7a -> keycode 0x0 [power]
Warning: no scancode found for keysym 122
26054@1525122638.453236:vnc_key_event_map down 0, sym 0x7a -> keycode 0x0 [power]
Warning: no scancode found for keysym 120
26054@1525122638.573424:vnc_key_event_map down 1, sym 0x78 -> keycode 0x0 [power]
Warning: no scancode found for keysym 120
26054@1525122638.661208:vnc_key_event_map down 0, sym 0x78 -> keycode 0x0 [power]
Warning: no scancode found for keysym 99
26054@1525122638.813381:vnc_key_event_map down 1, sym 0x63 -> keycode 0x0 [power]
Warning: no scancode found for keysym 99
26054@1525122638.901175:vnc_key_event_map down 0, sym 0x63 -> keycode 0x0 [power]
Warning: no scancode found for keysym 118
26054@1525122639.053377:vnc_key_event_map down 1, sym 0x76 -> keycode 0x0 [power]
Warning: no scancode found for keysym 118
26054@1525122639.157235:vnc_key_event_map down 0, sym 0x76 -> keycode 0x0 [power]
26054@1525122639.429336:vnc_key_event_map down 1, sym 0x2d -> keycode 0xc [minus]
26054@1525122639.516922:vnc_key_event_map down 0, sym 0x2d -> keycode 0xc [minus]
26054@1525122639.645149:vnc_key_event_map down 1, sym 0x2d -> keycode 0xc [minus]
26054@1525122639.724957:vnc_key_event_map down 0, sym 0x2d -> keycode 0xc [minus]
26054@1525122639.853274:vnc_key_event_map down 1, sym 0x2d -> keycode 0xc [minus]
26054@1525122639.957027:vnc_key_event_map down 0, sym 0x2d -> keycode 0xc [minus]
26054@1525122640.333131:vnc_key_event_map down 1, sym 0x3d -> keycode 0xd [equal]
26054@1525122640.428924:vnc_key_event_map down 0, sym 0x3d -> keycode 0xd [equal]
26054@1525122640.533062:vnc_key_event_map down 1, sym 0x3d -> keycode 0xd [equal]
26054@1525122640.620968:vnc_key_event_map down 0, sym 0x3d -> keycode 0xd [equal]
26054@1525122640.773267:vnc_key_event_map down 1, sym 0x3d -> keycode 0xd [equal]
26054@1525122640.860974:vnc_key_event_map down 0, sym 0x3d -> keycode 0xd [equal]
qemu-system-x86_64: terminating on signal 15 from pid 26078 (/usr/bin/python)`

**Comment by apoikos** [comment] 2018-06-07 14:30
I admin this doesn't make much sense. Reading the qemu code, there has to be either something wrong with the keymap file (e.g. qemu cannot load it), or somehow the name2keysym table (which is hardcoded at compile time) gets corrupted.

**Comment by sgsax** [comment] 2018-06-07 14:51
The problem doesn't appear to be with qemu, only how ganeti is invoking it. Running qemu manually does not trigger the bug. It only happens when using ganeti scripts.

**Comment by apoikos** [comment] 2018-06-07 14:54
Okay, I was going through my IRC backlog, so a couple of questions:

 - Does it also happen if you set *no* keymap at all, on both instance *and* cluster hypervisor parameters?
 - What was the mountpoint you were trying to mount using NFS?

**Comment by apoikos** [comment] 2018-06-07 15:16
Also, does it affect *already-running* instances, or instances started after the mount?

**Comment by apoikos** [comment] 2018-06-07 15:53
You can also give GDB a try: install qemu-system-x86-dbgsym (you'll need the debug lines in your /etc/apt/sources.list for that), attach a running QEMU **test** instance (`gdb -p <pid>`) and try issuing the following command:

```
(gdb) p/x vnc_displays.tqh_first->kbd_layout->keysym2keycode
$7 = {0x0 <repeats 32 times>, 0x39, 0x102, 0x128, 0x104, 0x105, 0x106, 0x108, 
  0x28, 0x10a, 0x10b, 0x109, 0x10d, 0x33, 0xc, 0x34, 0x35, 0xb, 0x2, 0x3, 0x4, 
  0x5, 0x6, 0x7, 0x8, 0x9, 0xa, 0x127, 0x27, 0x56, 0xd, 0x156, 0x135, 0x103, 
  0x11e, 0x130, 0x12e, 0x120, 0x112, 0x121, 0x122, 0x123, 0x117, 0x124, 0x125, 
  0x126, 0x132, 0x131, 0x118, 0x119, 0x110, 0x113, 0x11f, 0x114, 0x116, 0x12f, 
  0x111, 0x12d, 0x115, 0x12c, 0x1a, 0x2b, 0x1b, 0x107, 0x10c, 0x29, 0x1e, 0x30, 
  0x2e, 0x20, 0x12, 0x21, 0x22, 0x23, 0x17, 0x24, 0x25, 0x26, 0x32, 0x31, 0x18, 
  0x19, 0x10, 0x13, 0x1f, 0x14, 0x16, 0x2f, 0x11, 0x2d, 0x15, 0x2c, 0x11a, 0x856, 
  0x11b, 0x129, 0x0 <repeats 39 times>, 0x956, 0x0 <repeats 345 times>}

```

This will show us the actual keymap qemu has loaded at that point.

**Comment by apoikos** [comment] 2018-06-08 06:11
Also please paste the output of `cat /proc/<pid>/environ | xargs -0 -n 1` for the same instance to see what environment it's running with.

**Comment by apoikos** [comment] 2019-02-20 20:31
Closing this, as I'm unable to reproduce this without additional information. @sgsax, feel free to re-open it at will :)

**Closed by apoikos** 2019-02-20 20:31 UTC
