### ISSUE TITLE
Python 3 migration: critical issues found by pylint3

### ISSUE THREAD

**Issue by rbott** [ganeti/ganeti#1415] opened 2019-12-12 23:14 UTC
#1414 allows to run `make pylint` after the Python 3 migration again (at least when the package `pylint3` is installed).

I have attached the entire pylint3 output to this issue but will also include all *critical* errors in this post:
* ganeti/opcodes_base.py:149:11: E1121: Too many positional arguments for classmethod call (too-many-function-args)
* ganeti/opcodes_base.py:253:22: E1101: Instance of 'BaseOpCode' has no 'OP_ID' member (no-member)
* ganeti/opcodes_base.py:260:24: E1101: Instance of 'BaseOpCode' has no 'OP_ID' member (no-member)
* ganeti/opcodes_base.py:263:36: E1101: Instance of 'BaseOpCode' has no 'OP_ID' member (no-member)
* ganeti/errors.py:445:6: E0633: Attempting to unpack a non-sequence (unpacking-non-sequence)
* ganeti/opcodes.py:160:22: E1102: field_formatter is not callable (not-callable)
* ganeti/tools/burnin.py:1086:14: E0602: Undefined variable 'reduce' (undefined-variable)
* ganeti/jqueue/exec.py:72:4: E1101: Instance of 'closing' has no 'Call' member (no-member)
* ganeti/jqueue/exec.py:74:20: E1101: Instance of 'closing' has no 'Call' member (no-member)
* ganeti/client/gnt_cluster.py:2236:5: E0602: Undefined variable 'IsBelowDir' (undefined-variable)
* ganeti/hypervisor/hv_xen.py:1072:4: E1111: Assigning result of a function call, where the function has no return (assignment-from-no-return)
* ganeti/hypervisor/hv_lxc.py:96:11: E1101: Instance of 'LXCVersion' has no 'original_string' member (no-member)
* ganeti/utils/__init__.py:990:9: E0602: Undefined variable 'array' (undefined-variable)
* ganeti/utils/__init__.py:994:6: E0602: Undefined variable 'array' (undefined-variable)
* ganeti/utils/__init__.py:998:6: E0602: Undefined variable 'array' (undefined-variable)
* ganeti/utils/retry.py:54:32: E1136: Value 'self.args' is unsubscriptable (unsubscriptable-object)
* ganeti/utils/retry.py:55:12: E1136: Value 'self.args' is unsubscriptable (unsubscriptable-object)
* ganeti/utils/retry.py:57:26: E1133: Non-iterable value self.args is used in an iterating context (not-an-iterable)
* tools/ganeti-listrunner:522:11: E0602: Undefined variable 'file' (undefined-variable)
* tools/lvmstrap:417:0: E0001: invalid syntax (<unknown>, line 417) (syntax-error)
* daemons/import-export:140:34: E0602: Undefined variable 'long' (undefined-variable)
* autotools/check-header:141:34: E1101: Instance of 'zip' has no 'pop' member (no-member)

[pylint-output.txt](https://github.com/ganeti/ganeti/files/3958169/pylint-output.txt)

**Comment by apoikos** [comment] 2019-12-13 07:53
@rbott, thanks! Most of the issues are false positive, but there are a couple of findings (some of them broken before the Python 3 migration) that need to be fixed, see notes inline. I'll open a PR shortly.

> #1414 allows to run `make pylint` after the Python 3 migration again (at least when the package `pylint3` is installed).
> 
> I have attached the entire pylint3 output to this issue but will also include all _critical_ errors in this post:
> 
>     * ganeti/opcodes_base.py:149:11: E1121: Too many positional arguments for classmethod call (too-many-function-args)

False positive. `__new__` [is a static method](https://docs.python.org/3/reference/datamodel.html#object.__new__)

> 
>     * ganeti/opcodes_base.py:253:22: E1101: Instance of 'BaseOpCode' has no 'OP_ID' member (no-member)
> 
>     * ganeti/opcodes_base.py:260:24: E1101: Instance of 'BaseOpCode' has no 'OP_ID' member (no-member)
> 
>     * ganeti/opcodes_base.py:263:36: E1101: Instance of 'BaseOpCode' has no 'OP_ID' member (no-member)

These are probably hard for pylint to figure out: `OP_ID` is defined dynamically at class creation through the `_AutoOpParamSlots` metaclass. We should ignore these warnings.

>     * ganeti/errors.py:445:6: E0633: Attempting to unpack a non-sequence (unpacking-non-sequence)

False positive, `Exception.args` is a tuple.

>     * ganeti/opcodes.py:160:22: E1102: field_formatter is not callable (not-callable)

False positive, there's a check that `field_formatter` is callable, right at the previous line.

>     * ganeti/tools/burnin.py:1086:14: E0602: Undefined variable 'reduce' (undefined-variable)

Positive, `reduce` is no longer built-in, we need to import it from functools.

>     * ganeti/jqueue/exec.py:72:4: E1101: Instance of 'closing' has no 'Call' member (no-member)
> 
>     * ganeti/jqueue/exec.py:74:20: E1101: Instance of 'closing' has no 'Call' member (no-member)

False positives, `contextlib.closing` assumes the identity of the original object (the transport in this case) inside the `with:` statement.

>     * ganeti/client/gnt_cluster.py:2236:5: E0602: Undefined variable 'IsBelowDir' (undefined-variable)

Positive. That's part of a patch I merged from Debian, `IsBelowDir` should be fully qualified. I'll push a fix directly to master for that.
> 
>     * ganeti/hypervisor/hv_xen.py:1072:4: E1111: Assigning result of a function call, where the function has no return (assignment-from-no-return)

Positive, but it's a logical error. We expect `result` to be `None`, the problem is that it is *always* `None`.

>     * ganeti/hypervisor/hv_lxc.py:96:11: E1101: Instance of 'LXCVersion' has no 'original_string' member (no-member)

False positive, `original_string` is defined dynamically at class definition time using `__new__`.

>     * ganeti/utils/**init**.py:990:9: E0602: Undefined variable 'array' (undefined-variable)
> 
>     * ganeti/utils/**init**.py:994:6: E0602: Undefined variable 'array' (undefined-variable)
> 
>     * ganeti/utils/**init**.py:998:6: E0602: Undefined variable 'array' (undefined-variable)

My bad, forgot to import `array` in 493c901bd23c9a891a3426b0468a4db462058af3. I'll fix it and add a unittest.

>     * ganeti/utils/retry.py:54:32: E1136: Value 'self.args' is unsubscriptable (unsubscriptable-object)
> 
>     * ganeti/utils/retry.py:55:12: E1136: Value 'self.args' is unsubscriptable (unsubscriptable-object)
> 
No, it isn't :) (false positive)

>     * ganeti/utils/retry.py:57:26: E1133: Non-iterable value self.args is used in an iterating context (not-an-iterable)

Ditto
 
>     * tools/ganeti-listrunner:522:11: E0602: Undefined variable 'file' (undefined-variable)
Ah, missed this one when grep'ing for `file()`. It should be `open()` nowadays.

>     * tools/lvmstrap:417:0: E0001: invalid syntax (, line 417) (syntax-error)

Long literal (`512L`), not needed nor supported in Python 3.

> 
>     * daemons/import-export:140:34: E0602: Undefined variable 'long' (undefined-variable)

Reference to `long`. I missed that because it was not under `lib/` :/

>     * autotools/check-header:141:34: E1101: Instance of 'zip' has no 'pop' member (no-member)

Yes, `zip` has no `pop()`, it should be written as `next(lines)`.

**Closed** 2019-12-17 09:54 UTC
