### ISSUE TITLE
Add an option to disable document building

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#489] opened 2017-06-23 04:26 UTC
Originally reported of Google Code with ID 433.

```
The current Ganeti tarball contains pre-built HTML documentation, but it always builds the entire documentation. Add a mechanism to disable the documentation building. The most obvious solution is adding something like --disable-doc to ./configure.
```
Originally added on 2013-04-22 23:25:21 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment] 2017-06-23 04:27
```
Could you please provide more information about which behavior you are seeing?

Doing the canonical unpacking, ./configure && make the only form of rebuilding
that I can see is the sed -f autotools/replace_vars.sed < .. > ...; this, however,
is necesarry, as paths are substituted in that can be changed at configure time
```
Originally added on 2013-04-23 08:16:20 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment] 2017-06-23 04:27
```
-- Empty comment --
```
Originally added on 2013-04-23 08:19:56 +0000 UTC.

Changed State: NeedFeedback

**Comment by Ganeti-Issues-Migrator** [comment] 2017-06-23 04:28
```
For context, I am working on the Arch Linux package for Ganeti. I attached the draft PKGBUILD file (approximately equivalent to Debian's rules + control). The prepare(), build(), and package() functions are the most important.

I think something else might be going wrong. Sphinx always tries to run, regardless of whether the sphinx-build executable is available or not. There is a rule in the top level Makefile.am (doc/html/index.html) that exits with 1 if sphinx is not installed. That rule always runs on both my personal computer and a friend's computer. Both are running Arch. The package builds successfully if Sphinx is available.
```
Originally added on 2013-04-24 03:25:54 +0000 UTC.

Attachments: 
[PKGBUILD](https://storage.googleapis.com/google-code-attachments/ganeti/issue-433/comment-3/PKGBUILD)

**Comment by Ganeti-Issues-Migrator** [comment] 2017-06-23 04:33
```
I think the problem there is with "autoreconf": could you try to do that without regenerating the configure script, but just using the one provided in the package? That way it should be able to use the prebuilt documentation.

Thanks,

Guido

```
Originally added on 2013-04-24 09:15:53 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment] 2017-06-23 04:34
```
Also changing Makefile.am doesn't help: perhaps you want to execute your "sed" on the resulting scripts *after* the build happens, rather than in the "prepare" phase.
```
Originally added on 2013-04-24 09:19:18 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment] 2017-06-23 04:37
```
The build system has problems with a version mismatch (autotools 1.11 vs 1.13). If I don't run autoreconf, I get complaints.

Alas, there are various areas in the build system that refer to /usr/bin/python, so I have to do the substitution in the prepare() function. I tried moving the substitution and the build failed with Python 3-related SyntaxErrors.

Would it be easier for me to just patch Makefile.am so that it doesn't give an error? If no one else has this issue, I'm okay with a route that's not ideal.
```
Originally added on 2013-04-25 06:02:32 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment] 2017-06-23 04:38
```
I see, thanks for the explanation.

I guess for your case, then, disabiling doc building explicitly is required. As a workaround does "touching" all docs after ./configure help at all avoiding the rebuild? (I know, it's ugly, but perhaps it allows you to package right away, while a proper fix trickles into a release).

We also would love a good way to pass the python interpreter: this can be done easily in makefile, but all other .py files are more problematic (we don't want to move them to .py.in just for the python shebang.

If you want to send patches to improve the buildsystem they are definitely very welcome.

Thanks,

Guido


```
Originally added on 2013-04-25 07:50:37 +0000 UTC.

Changed State: Accepted

**Comment by Ganeti-Issues-Migrator** [comment] 2017-06-23 04:38
```
Would using:
#!/usr/bin/env python
help to make things more flexible?

This way just changing its own PATH the user would be able to select the python version.
```
Originally added on 2013-04-25 07:59:50 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment] 2017-06-23 19:42
```
-- Empty comment --
```
Originally added on 2013-12-09 14:34:42 +0000 UTC.

Added Labels: Type-Enhancement

**Comment by ge-fa** [comment] 2018-09-26 13:03
@apoikos That's not an issue on Debian at least, I guess? If so, I would propose to close this one.

new state: should be closed

**Comment by apoikos** [comment] 2018-09-26 13:20
In this case the documentation got rebuild because the files in the source were changed by the `sed` command. This is expected behavior and patching Makefile to remove the dependencies from `doc/html/index.html` would be a workaround. Therefore, I agree with @ge-fa that this bug should be closed;

**Comment by iustin** [comment] 2018-09-26 20:00
+1, closing.

**Closed by iustin** 2018-09-26 20:00 UTC
Labels: AutoMigrated, Status:Accepted, Type-Enhancement
