### ISSUE TITLE
[Feature Request] Option to change DRBD_META_SIZE at cluster level

### ISSUE THREAD

**Issue by zen2** [ganeti/ganeti#1758] opened 2024-07-23 15:25 UTC
Actual DRBD meta disk size is hardcoded in /usr/share/ganeti/default/ganeti/_constants.py with a value of 128 MiB.
This permit DRBD volume up to 4TiB.

These limits are too much restrictive for actual storage size.
On our cluster we already have modified these values to DRBD 8.4 maximum limits : DRBD_META_SIZE = 1 GiB with a corresponding DRBD DATA storage limit of 32 TiB with no particular problem at all these last 10 years.
Note: DRBD 9.4 raise the data size limit to 1PiB.

We have set it by default in ganeti code and so it is used for all our volume as that permit us to grow disk easily through volume life time. Particularly for performance reason, metadata volume group is backed by SSD while data volume group is backed by conventional SAS drive raid system. We manage around 100 disks for a cluster total DRBD metadata size of 100 GiB and a real DRBD data size usage of ~150 TiB on ~190 TiB capacity.

So I understand that ganeti usage can be really different depending on usage scenario: that can be thousands of little volumes but that can be dozen of huge volumes too or mix of both.

An old conversation on this particular topic was to have a dynamic metadata size calculated on initial data size.
We realize that it was a wrong way to handle storage size since we are currently and for years now using instance grow-disk command that use a ganeti hook perfectly for many years.

So it could be good with appropriate documentation that explains DRBD metadata/data size limits to make the actual constant DRBD_META_SIZE variable become a cluster parameter to let administrators set it for their storage usage.

**Comment by saschalucas** [comment] 2024-08-01 18:28
Seems like a duplicate of #1641? Therefore I'm closing this issue. If you think this is wrong, feel free to repoen

**Closed by saschalucas** 2024-08-01 18:28 UTC
