### ISSUE TITLE
Notify KVM instances after growing disks

### ISSUE THREAD

**Issue by apoikos** [ganeti/ganeti#1549] opened 2020-12-28 18:49 UTC
Disks are currently able to grow online, but KVM instances must be explicitly notified to allow the guest OS to use the extra capacity without a hypervisor restart. This is relatively simple to implement and should be enabled by default.

**Comment by saschalucas** [comment] 2020-12-28 21:21
this seems a duplicate of issue #28.

**Comment by codefritzel** [comment] 2024-09-12 13:43
closed by #1731

**Closed by codefritzel** 2024-09-12 13:43 UTC
