### ISSUE TITLE
Support for Python 3.10/3.11 needed

### ISSUE THREAD

**Issue by robbat2** [ganeti/ganeti#1687] opened 2022-11-29 23:54 UTC
There was a previous PR for Python3.8 support, but it's not clear further Python work has taken place to support Python 3.9/3.10/3.11.

Upstream Python has both 3.8 & 3.9 series in security-only fixes.

Is there an effort to support newer Python yet, before distributions start to remove Python 3.8? (Gentoo is discussing removal of 3.8 already).

**Comment by jfut** [comment] 2022-11-30 03:31
For your information, at least on Python 3.9.14 on RHEL/AlmaLinux/Rocky Linux 9, all `make py-tests` succeed and works fine.

`make py-tests` results:
https://github.com/jfut/ganeti-rpm/issues/50#issuecomment-1255719822

My test environment:

```bash
[jfut@node01.example.org ~]$ cat /etc/redhat-release
AlmaLinux release 9.1 (Lime Lynx)

[jfut@node01.example.org ~]$ ps aux | grep ganeti
gnt-con+     878  0.0  0.0 1073993796 19756 ?    Ss   Nov21   1:23 /usr/sbin/ganeti-confd -f
root         883  0.0  0.0 1073983660 12708 ?    Ss   Nov21   0:01 /usr/sbin/ganeti-kvmd -f
root         887  0.0  0.8 264416 264304 ?       SLs  Nov21   0:14 /usr/bin/python3 /usr/sbin/ganeti-noded -f
gnt-mas+     892  0.0  0.0 1073998356 27676 ?    Ss   Nov21   0:30 /usr/sbin/ganeti-wconfd -f
gnt-mas+    1100  0.0  0.0 1073998288 30264 ?    Ss   Nov21   3:00 /usr/sbin/ganeti-luxid -f
gnt-rapi    1101  0.0  0.1 256924 34516 ?        Ss   Nov21   0:03 /usr/bin/python3 /usr/sbin/ganeti-rapi -f -b 127.0.0.1 --require-authentication
gnt-met+    5568  0.0  0.0 1073988936 13376 ?    Ss   Nov21   0:00 /usr/sbin/ganeti-metad -f
jfut      227665  0.0  0.0 221796  2368 pts/0    S+   11:58   0:00 grep --color=auto ganeti

[jfut@node01.example.org ~]$ /usr/bin/python3 -V
Python 3.9.14

[jfut@node01.example.org ~]$ rpm -qa | grep python3-3
python3-3.9.14-1.el9_1.1.x86_64
```

**Comment by saschalucas** [comment] 2023-03-06 21:53
Hi @robbat2,

Ganeti has its home in Debian. So as long as you can find Ganeti in there, one can assume that the currently distributed Debian version of python is supported.

As of now, this is python-3.11 in Debian Bookworm. I can confirm, that `py-tests` succeeds in Bookworm with a some deprecation warnings:
```
     16  currentThread() is deprecated, use current_thread() instead
     17  getName() is deprecated, get the name attribute instead
      2  isSet() is deprecated, use is_set() instead
      4  notifyAll() is deprecated, use notify_all() instead
      1  setName() is deprecated, set the name attribute instead
      1  The asynchat module is deprecated and will be removed in Python 3.12. The recommended replacement is asyncio
      1  The asyncore module is deprecated and will be removed in Python 3.12. The recommended replacement is asyncio
```
So next stop is 3.12.

If that information suits your needs, feel free to close this issue.

**Comment by apoikos** [comment] 2023-03-07 11:20
The threading deprecation warnings should be trivial to fix, as long as they don't break backward compatibility with Python >= 3.6. The asynchat/asyncore changes are more complicated, and are probably a good excuse to refactor the core event loop.

**Comment by apoikos** [comment] 2023-03-08 15:31
I have some good news regarding asyncore/asynchat. The code using asynchat (`daemon.AsyncTerminatedMessageStream`) is actually dead code that has been unused since LuxiD replaced masterd and can be completely removed. The remaining code using asyncore contains a lot of unused functionality (e.g. event timers) that can be removed, making rewriting for asyncio easier than it looks. I'll have a stab at it when I find some time.

**Comment by rbott** [comment] 2023-05-25 14:53
Currently Python 3.10/3.11 support looks good, so I'll move forward and close this issue. Thanks for your work @apoikos!

**Closed by rbott** 2023-05-25 14:53 UTC
