### ISSUE TITLE
Hail fails with FailN1 for an EXT instance allocation in 2.16

### ISSUE THREAD

**Issue by yiannist** [ganeti/ganeti#51] opened 2017-06-13 13:48 UTC
Hey,

A strange issue caught our attention when trying to update snf-ganeti to 2.16. Hail fails to allocate an instance with EXT disk template. This used to work in 2.15.

The output:
```
➜ ok0-mc1.dev /var/log/ganeti  # gnt-instance add -I hail -o snf-image+jessie -B memory=2G,vcpus=4 -t ext --disk=0:size=10G,provider=rbd,name=alexvol --net 0:network=snf-net-1,ip=pool --no-name-check --no-ip-check test                                           
Failure: prerequisites not met for this operation:
error type: insufficient_resources, error details:
Can't compute nodes using iallocator 'hail': Request failed: Group default (preferred): No valid allocation solutions, failure reasons: FailN1: 3
```
while with `-n` everything works as expected:
```
➜ ok0-mc1.dev /var/log/ganeti  # gnt-instance add -n ok0-00.dev.okeanos.grnet.gr -o snf-image+jessie -B memory=2G,vcpus=4 -t ext --disk=0:size=10G,provider=rbd,name=alexvol --net 0:network=snf-net-1,ip=pool --no-name-check --no-ip-check test
Thu Jun  8 11:50:54 2017  - INFO: NIC/0 inherits netparams ['snf-link-1', 'routed', u'']
Thu Jun  8 11:50:54 2017  - INFO: Chose IP <ip> from network snf-net-1
Thu Jun  8 11:50:55 2017 * disk 0, size 10.0G
Thu Jun  8 11:50:55 2017 * creating instance disks...
Thu Jun  8 11:50:56 2017 adding instance test to cluster config
Thu Jun  8 11:50:56 2017 adding disks to cluster config
Thu Jun  8 11:50:56 2017  - INFO: Waiting for instance test to sync disks
Thu Jun  8 11:50:57 2017  - INFO: Instance test's disks are in sync
Thu Jun  8 11:50:57 2017  - INFO: Waiting for instance test to sync disks
Thu Jun  8 11:50:57 2017  - INFO: Instance test's disks are in sync
Thu Jun  8 11:50:57 2017 * running the instance OS create scripts...
Thu Jun  8 11:51:53 2017 * starting instance...
```
The same goes with DRBD disks:
```
➜ ok0-mc1.dev /var/log/ganeti  # gnt-instance add -I hail -o snf-image+jessie -B memory=2G,vcpus=4 -t drbd --disk=0:size=10G --net 0:network=snf-net-1,ip=pool --no-name-check --no-ip-check test
Thu Jun  8 14:15:51 2017  - INFO: Selected nodes for instance test via iallocator hail: ok0-01.dev.okeanos.grnet.gr, ok0-00.dev.okeanos.grnet.gr
Thu Jun  8 14:15:51 2017  - INFO: NIC/0 inherits netparams ['snf-link-1', 'routed', u'']
Thu Jun  8 14:15:51 2017  - INFO: Chose IP <ip> from network snf-net-1
Thu Jun  8 14:15:53 2017 * creating instance disks...
```

So, I tried to debug this with `gnt-debug` (thanks @apoikos!):
```
root@ok0-mc1:~# gnt-debug allocator --dir in --mode allocate --mem 2G --disks 1G -t ext -o no_such_os no_such_instance > h-alloc-ext.json
root@ok0-mc1:~# /usr/lib/ganeti/iallocators/hail -v -p h-alloc-ext.json 
Received request: Allocate (Instance {name = "no_such_instance", alias = "no_such_instance", mem = 2048, dsk = 1024, disks = [Disk {dskSize = 1024, dskSpindles = Nothing}], vcpus = 1, runSt = Running, pNode = 0, sNode = 0, idx = -1, util = DynUtil {cpuWeight = 1.0, memWeight = 1.0, dskWeight = 1.0, netWeight = 1.0}, movable = True, autoBalance = True, diskTemplate = DTExt, spindleUse = 1, allTags = [], exclTags = [], dsrdLocTags = fromList [], locationScore = 0, arPolicy = ArNotEnabled, nics = [Nic {mac = Just "00:11:22:33:44:55", ip = Nothing, mode = Nothing, link = Nothing, bridge = Nothing, network = Nothing}], forthcoming = False}) (AllocDetails 1 Nothing) Nothing

Initial cluster status:
 F Name                          t_mem n_mem i_mem x_mem  f_mem  u_mem r_mem t_dsk f_dsk pcpu vcpu pcnt scnt    p_fmem p_fdsk r_cpu   lCpu   lMem   lDsk   lNet
   ok0-02.dev.okeanos.grnet.gr  193809  4096  3072 -5372 192013 186641  7168     0     0   24   47   16    7    0.9630 1.0000  1.96 16.000 16.000 23.000 16.000
 - ok0-mc1.dev.okeanos.grnet.gr      0  4096     0 -4096      0  -4096     0     0     0    0    0    0    0 -Infinity 1.0000   NaN  0.000  0.000  0.000  0.000
 - ok0-mc2.dev.okeanos.grnet.gr      0  4096     0 -4096      0  -4096     0     0     0    0    0    0    0 -Infinity 1.0000   NaN  0.000  0.000  0.000  0.000
   ok0-00.dev.okeanos.grnet.gr  193809  4096  5120 -7049 191642 184593  4096     0     0   24   49   17    5    0.9524 1.0000  2.04 17.000 17.000 22.000 17.000
 - ok0-mc0.dev.okeanos.grnet.gr      0  4096     0 -4096      0  -4096     0     0     0    0    0    0    0 -Infinity 1.0000   NaN  0.000  0.000  0.000  0.000
   ok0-01.dev.okeanos.grnet.gr  193809  4096  4096 -6023 191640 185617  8192     0     0   24   48   17    6    0.9577 1.0000  2.00 17.000 17.000 23.000 17.000

{"success":false,"info":"Request failed: Group default (preferred): No valid allocation solutions, failure reasons: FailN1: 3","result":[]}

Final cluster status:
 F Name                          t_mem n_mem i_mem x_mem  f_mem  u_mem r_mem t_dsk f_dsk pcpu vcpu pcnt scnt    p_fmem p_fdsk r_cpu   lCpu   lMem   lDsk   lNet
   ok0-02.dev.okeanos.grnet.gr  193809  4096  3072 -5372 192013 186641  7168     0     0   24   47   16    7    0.9630 1.0000  1.96 16.000 16.000 23.000 16.000
 - ok0-mc1.dev.okeanos.grnet.gr      0  4096     0 -4096      0  -4096     0     0     0    0    0    0    0 -Infinity 1.0000   NaN  0.000  0.000  0.000  0.000
 - ok0-mc2.dev.okeanos.grnet.gr      0  4096     0 -4096      0  -4096     0     0     0    0    0    0    0 -Infinity 1.0000   NaN  0.000  0.000  0.000  0.000
   ok0-00.dev.okeanos.grnet.gr  193809  4096  5120 -7049 191642 184593  4096     0     0   24   49   17    5    0.9524 1.0000  2.04 17.000 17.000 22.000 17.000
 - ok0-mc0.dev.okeanos.grnet.gr      0  4096     0 -4096      0  -4096     0     0     0    0    0    0    0 -Infinity 1.0000   NaN  0.000  0.000  0.000  0.000
   ok0-01.dev.okeanos.grnet.gr  193809  4096  4096 -6023 191640 185617  8192     0     0   24   48   17    6    0.9577 1.0000  2.00 17.000 17.000 23.000 17.000
```
While with DRBD:
```
root@ok0-mc1:~# gnt-debug allocator --dir in --mode allocate --mem 2G --disks 10G -t drbd -o no_such_os no_such_instance > h-alloc-drbd.json
root@ok0-mc1:~# /usr/lib/ganeti/iallocators/hail h-alloc-drbd.json 
{"success":true,"info":"Request successful: Selected group: default, Group default (preferred): score: 0.57086361, successes 6, failures 0 () for node(s) ok0-02.dev.okeanos.grnet.gr/ok0-00.dev.okeanos.grnet.gr","result":["ok0-02.dev.okeanos.grnet.gr","ok0-00.dev.okeanos.grnet.gr"]}
```
(also, `hail` works as expected using `--no-capacity-checks`)

Trying to reduce the output of the `gnt-debug allocator` command I noticed that the problem appears when there is an existing DRBD instance in the cluster and we try to allocate an EXT instance. A minimal input file for hail that triggers the error is [here](https://gist.github.com/yiannist/8ac7ec981ab6ea38f71747bf0b213bc5). This makes hail fail with `FailN1` in 2.16 while it works fine in 2.15!

I tried to solve this but I'm not sure that I get this straight! Let me give it a shot:
- When trying to allocate an EXT instance, cluster status reports total and free disk space (`t_dsk`/`f_dsk`) 0 as the EXT resources are not "accountable"
- `hail` tries to test for N+1 redundant allocation by invoking `canEvacuateNode` (in `src/Ganeti/HTools/GlobalN1.hs`)
- `canEvacuateNode` tries to failover DRBD instances by invoking `move` (from `src/Ganeti/HTools/Cluster/Moves.hs`) with `Failover`
- `move` invokes `applyMoveEx` (same file) with `force = True` and `Failover`
- `applyMoveEx` calls `addPriEx` which tries to compute `new_dsk_forth` with `decIf uses_disk (fDskForth t) (Instance.dsk inst)` where `uses_disk = Instance.usesLocalStorage inst` and `localStorageTemplates = [ T.DTDrbd8, T.DTPlain ]`.
- This results in `new_dsk_forth <= 0` which raises a `Bad T.FailDisk`
- The `FailDisk` appears as an `FailN1` because of failed monadic computations in `collectionToSolution` (in `src/Ganeti/HTools/Cluster/AllocationSolution.hs`)

This might be triggered by @aehlig's commit which enables the N+1 redundancy in `tryAlloc`:
```
commit 02132b44fd7471c02891f11ce41971d301227b70
Author: Klaus Aehlig <aehlig@google.com>
Date:   Fri Apr 17 14:54:28 2015 +0200

    Make tryAlloc honor global N+1 redundancy

    When looking for an allocation, make htools restrict to
    those that are globally N+1 redundant. As checking for
    N+1 redundancy is an expensive operation, we first
    look for the best allocations and filter out later.

    For the time being, we do not change the semantics of
    iterateAlloc; i.e., for iterateAlloc we will pretend
    that capacity checks are ignored.

    Signed-off-by: Klaus Aehlig <aehlig@google.com>
    Reviewed-by: Petr Pudlak <pudlak@google.com>
```

Then again, the above scenario might not make any sense! :) Anyway, we think that this is a rather serious issue that might even be blocking for the next release... 

Let me know if I can help somehow!

On a side note, it seems a bit strange to me that `n_mem` is different in 2.15 and 2.16 but I 'd say that this has nothing to do with the reported issue.

**Comment by yiannist** [comment] 2017-06-19 12:03
We verified our assumptions (with @philipgian) by doing profiling on Hail (that was a crazy experience by the way!). The following dirty-fix disables the `FailDisk` check for the DRBD instance and allows the `hail` allocator to decide:
```
diff --git a/src/Ganeti/HTools/Node.hs b/src/Ganeti/HTools/Node.hs
index d5c4f1c..dfa5db1 100644
--- a/src/Ganeti/HTools/Node.hs
+++ b/src/Ganeti/HTools/Node.hs
@@ -942,7 +942,7 @@ addPriEx force t inst =
                                 $ getLocationExclusionPairs t inst
       in case () of
         _ | new_free_mem <= 0 -> Bad T.FailMem
-          | uses_disk && new_dsk <= 0 -> Bad T.FailDisk
+ --         | uses_disk && new_dsk <= 0 -> Bad T.FailDisk
           | strict && uses_disk && new_dsk < loDsk t -> Bad T.FailDisk
           | uses_disk && exclStorage t && new_free_sp < 0 -> Bad T.FailSpindles
           | strict && uses_disk && new_inst_sp > hiSpindles t -> Bad T.FailDisk
@@ -1023,7 +1023,7 @@ addSecExEx ignore_disks force t inst pdx =
 
       checkForthcomingViolation
         | not (Instance.hasSecondary inst)       = Bad T.FailDisk
-        | new_dsk_forth <= 0                     = Bad T.FailDisk
+        | ignore_disks && new_dsk_forth <= 0     = Bad T.FailDisk -- Hack to avoid 'warn-unused' for ignore_disks
         | new_dsk_forth < loDsk t                = Bad T.FailDisk
         | exclStorage t && new_free_sp_forth < 0 = Bad T.FailSpindles
         | new_inst_sp_forth > hiSpindles t       = Bad T.FailDisk
@@ -1053,7 +1053,7 @@ addSecExEx ignore_disks force t inst pdx =
                new_slist = iname:sList t
       in case () of
         _ | not (Instance.hasSecondary inst) -> Bad T.FailDisk
-          | not ignore_disks && new_dsk <= 0 -> Bad T.FailDisk
+--          | not ignore_disks && new_dsk <= 0 -> Bad T.FailDisk
           | strict && new_dsk < loDsk t -> Bad T.FailDisk
           | exclStorage t && new_free_sp < 0 -> Bad T.FailSpindles
           | strict && new_inst_sp > hiSpindles t -> Bad T.FailDisk
```
I'm very interested in providing a proper fix for this but this seems a bit intrusive for the iallocator logic and I do not feel very confident for it.

**Comment by philipgian** [comment] 2017-06-19 14:16
As a workaround, I've added the `--no-capacity-checks` options to the `default-iallocato-params` cluster configuration option:
`gnt-cluster modify --default-iallocator-params='-no-capacity-checks'`

It seems to work, bypassing the new `GlobalN+1` checks.

From the documentation:
```
--no-capacity-checks
 Normally, hspace will only consider those allocations where all instances
 of a node can immediately restarted should that node fail. With this
 option given, hspace will check only N+1 redundancy for DRBD instances.
```

From the NEWS:

```
- ``htools`` now also take into account N+1 redundancy for plain and shared
 storage. To obtain the old behavior, add the ``--no-capacity-checks`` option.
```

**Comment by irregulator** [comment] 2017-11-10 11:42
Hey fellas,

any update on this issue? Is there a fix coming?

**Comment by dannyman** [comment] 2020-09-08 03:48
I am hitting this issue on 2.16.1 on a cluster with ample capacity.

```
Can't compute nodes using iallocator 'hail': Request failed: Group default (preferred): No valid allocation solutions, failure reasons: FailMem: 26, FailN1: 30
```

Applying `gnt-cluster modify --default-iallocator-params='-no-capacity-checks'` fixes the immediate issue.

**Comment by rbott** [comment] 2020-09-08 07:06
You can also try and see what `hspace` tells you:

```
# with RAPI endpoint
hspace -m https://$user:$pass@ganeti.master.node:5080 --disk-template=drbd --standard-alloc=20480,2048,2

# locally on master
hspace -L --disk-template=drbd --standard-alloc=20480,2048,2
```

Of course you may have to adapt `--disk-template` or `--standard-alloc` to your needs. You can also add `-v` for increased verbosity.

**Comment by iustin** [comment] 2020-09-08 07:18
I haven't seen this issue before; I'll try to take a look in the next ~2 weeks…

**Comment by iustin** [comment] 2020-09-08 07:20
In the meantime, if anyone can gather a cluster state file (as generated by `hscan`) it would be easier to try and reproduce.

**Comment by lickdragon** [comment] 2020-09-08 16:22
Is this the same bug?:
https://github.com/ganeti/ganeti/issues/51

**Comment by skorpy2009** [comment] 2020-09-08 17:58
@iustin 
```
Name  Nodes  Inst BNode BInst  t_mem  f_mem t_disk f_disk      Score
LOCAL     1    11     0     0  96659  46122    408     68 0.00000000
```

**Comment by iustin** [comment] 2020-09-08 21:32
@skorpy2009 - this is just the printed output. What matters is the actual cluster state, saved by hscan. By default it saves a file n the current directory, named as `<cluster_name>.data`. That file allows one to re-play hail/hbal/etc. via the `-t argument`, and would be good to try and reproduce.

**Comment by dannyman** [comment] 2020-09-23 18:41
Sent you an email, iustin. Thanks!

**Comment by dannyman** [comment] 2020-09-23 18:48
Is this what I want to see after `gnt-cluster modify --default-iallocator-params='-no-capacity-checks'`?

```
  default instance allocator parameters: 
    no-capacity-checks: None
```

The double-negative leaves some room for ambiguity ...

**Comment by rbott** [comment] 2020-10-12 15:44
We also ran into this problem on one of our production clusters today. The only intermediate fix was to add the `-no-capacity-checks` parameter. Interestingly, `hspace` reports 70 possible standard allocations (with parameters `--disk-template=drbd --standard-alloc=20480,2048,2`) whereas hail is not able to allocate a new instance (with the same allocation parameters):

```
Can't compute nodes using iallocator 'hail': Request failed: Group hw2020 (preferred): No valid allocation solutions, failure reasons: FailN1: 20, Group hw2015 (last_resort): No valid allocation solutions, failure reasons: FailMem: 20, FailN1: 90
```
We have attached the (anonymized) output of `hscan`. Maybe someone else is able to make heads or toes out of this.

On a side note: we removed a bunch of unused instances to free up space but we still received the same FailN1 error message. We also balanced the cluster using `hbal`, which increased the number of allocatable instances from 65 to 70 from an `hspace`-point of view.

[hscan.txt](https://github.com/ganeti/ganeti/files/5366101/hscan.txt)

**Comment by rbott** [comment] 2020-10-28 08:05
Just a quick sidenote: it _might_ be related to https://github.com/ganeti/ganeti/commit/d648887bbdba2fb513a2b24b1b05dcf839739d71

But I have not yet fully understood the consequences of that commit.

**Comment by rbott** [comment] 2021-02-13 16:20
I have done some more testing here. It looks like we actually *did* run into a FailN1 scenario here. To validate this I wrote a quick and hacky [script](https://github.com/rbott/ganeti-instance-allocation-test) which runs against a saved cluster state (run `hscan -L` on the Ganeti master to generate that).

The script tries to parse the data and you can ask it to "remove" any given node from the cluster by moving all primary/secondary instances somewhere else. It currently takes into account:
* memory
* disk usage (but assumes DRBD storage!)
* spindle count/ratio
* vCPU count/ratio
* allocation tags (e.g. to avoid running instances on the same primary node)

If it **does** fail, chances are good you actually do have a FailN1 problem :-) 

As I said it is rather hacky and I might have forgotten things Ganeti/hail take into account or mis-implemented them. But feel free to run this against your cluster data and maybe it helps someone else as well.

**Comment by rbott** [comment] 2024-05-18 16:45
I'll move forward here and close this issue as there have been no updates, new reports etc.

We can also re-open it if the issue still persists for users.

**Closed** 2024-05-18 16:52 UTC

**Comment by alfonso-escribano** [comment] 2026-04-28 09:44
I have this issue, a ganeti cluster version 3.0.2, with drbd and plain templates and 100 instances, now we have added ceph storage with ext provider, and I have to specify the primary node or set "--no-capacity-checks" option for iallocator params.
We have other ganeti cluster version 3.0.2 with only ceph storage with ext template and more than 60 instances that works without problems.
We use ext storage for ceph due to we need to have several different pools, and options to manipulate ceph rbd (replicated and EC) images from ganeti cluster.

Using --no-capacity-checks, can suppouse any problem rebalancing the cluster or when we need to evacuated a node?
